name: Checks

on: [push, pull_request]

jobs:
  codeQuality:
    runs-on: ubuntu-latest
    name: Code Quality
    steps:
      - name: Checkout changes
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Install PHP and PHP Code Sniffer
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
          tools: phpcs
      - name: Run code quality checks
        run: phpcs --colors --extensions="php" .
